// Excersizes 1: 0818 
var mainDiv = document.createElement("div");
mainDiv.setAttribute("id", "main-div");
document.body.appendChild(mainDiv);
var firstP = document.createElement("p");
var newText = document.createTextNode("Hello WORLD! A little bit about me.. all of my hopes and dreams and hopes and other dreams all require that I master the skill: the ultimate skill: making the perfect bowl of baked mac & cheese like thanksgivings good. So good ya eat it until CHRISTMAS and think about it all new years.");
mainDiv.appendChild(firstP);
firstP.appendChild(newText);
var btn = document.createElement("Button");
var btnText = document.createTextNode("this is da button");
btn.appendChild(btnText);
mainDiv.appendChild(btn);
var secondP = document.createElement("p");
var moreText = document.createTextNode("This is the second paragraph. Where you are supposted to learn more. What about? I literally have no idea..... Have you seen the Eric Andre show? It's got some funny bits but mostly I'm just like..... what the f? Rick and Morty is also another one a lot of wtf moments but its funny like the whole way thru. Shout out to cartoon network man.");
mainDiv.appendChild(secondP);
secondP.appendChild(moreText);
firstP.setAttribute("class", "paragraph-text");
secondP.setAttribute("class", "paragraph-text");
var orderedList = document.createElement("ol");
mainDiv.appendChild(orderedList);
var liOne = document.createElement("li");
var liTwo = document.createElement("li");
var liThree = document.createElement("li");
var liFour = document.createElement("li");
var liFive = document.createElement("li");
orderedList.appendChild(liOne);
orderedList.appendChild(liTwo);
orderedList.appendChild(liThree);
orderedList.appendChild(liFour);
orderedList.appendChild(liFive);
liOne.setAttribute("class", "list-item");
liTwo.setAttribute("class", "list-item");
liThree.setAttribute("class", "list-item");
liFour.setAttribute("class", "list-item");
liFive.setAttribute("class", "list-item");
orderedList.setAttribute("id", "main-list");
